# Generated by Django 2.1 on 2018-08-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('open_date', models.DateField()),
                ('ticket_description', models.TextField(max_length=300)),
                ('hours_to_complete', models.IntegerField()),
                ('status', models.CharField(choices=[('Research', 'Reasearch'), ('Coding', 'Coding'), ('QA', 'QA'), ('UAT', 'UAT'), ('Staging', 'Staging'), ('Completed', 'Completed')], default='Research', max_length=10)),
            ],
        ),
    ]
